spring.application.name=api-gateway

# base path of the application
server.port = 8081

# JWT Secrets
#time in milliseconds i.e 15 minutes = 900000 milliseconds
#secret key must be minimum of 32 bytes
jwt.secret=${JWT_SECRET}
jwt-access-token-expiration=900000
jwt-refresh-token-expiration=2592000000


# Spring Cloud Gateway Configuration 
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/auth/(?<segment>.*),/api/v1/auth/${segment}

# Debug
logging.level.org.springframework.cloud.gateway=DEBUG