spring.application.name=api-gateway

# base path of the application
server.port = 8081

# Disable AWS Secrets Manager lookup during tests
spring.cloud.aws.secretsmanager.enabled=false

# Get secrets from AWS Secrets Manager with store name prod/linkdlyst 
# AWS Secrets Manager
spring.config.import=aws-secretsmanager:prod/linkdlyst


# Here getting JWT_SECRET value from AWS Secrets Manager and using it in the application.properties file

# JWT Secrets
#time in milliseconds i.e 15 minutes = 900000 milliseconds
#secret key must be minimum of 32 bytes
# Here when the projeects starts then it will fetch this JWT_SECRET value from AWS Secrets Manager and use it in the application.properties file
jwt.secret=${JWT_SECRET}
jwt-access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
jwt-refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION}


# Spring Cloud Gateway Configuration 
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/auth/(?<segment>.*),/api/v1/auth/${segment}

# URL Endpoints routing configuration
spring.cloud.gateway.server.webflux.routes[0].id=url-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/urls/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/urls(?<segment>/?.*),/api/v1/urls${segment}

# Debug
logging.level.org.springframework.cloud.gateway=DEBUG