spring.application.name=api-gateway

# base path of the application
server.servlet.context-path=/api

#JWT Secrets
#time in milliseconds i.e 15 minutes = 900000 milliseconds
#secret key must be minimum of 32 bytes
jwt.secret=${JWT_SECRET}
jwt-access-token-expiration=900000
jwt-refresh-token-expiration=2592000000